name: MOT_workspace

channels:
  - default
  - conda-forge

dependencies:
  - python = 3.10
  - numpy<2.4
  - jupyter
  - scipy = 1.8
  - sympy
  - magpylib>5.0
  - plotly
  - pip
  - pip:
    - ARC-Alkali-Rydberg-Calculator